services:
  # Backend API service
  - type: web
    name: balbers-drop-spike-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: balbers-drop-spike-db
          property: connectionString
      - key: STOCK_API_KEY
        value: demo # Replace with your Alpha Vantage API key

  # Frontend service
  - type: web
    name: balbers-drop-spike-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist/frontend
    envVars:
      - key: NODE_VERSION
        value: 16.13.0

databases:
  - name: balbers-drop-spike-db
    plan: free
